services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban
      POSTGRES_DB: kanban
    ports:
      - '5434:5432'
    volumes:
      - kanban_postgres_data:/var/lib/postgresql/data

volumes:
  kanban_postgres_data:
